/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_vol (void)
{
  GtkWidget *espace_vol;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *combobox1;
  GtkWidget *ajvol;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *modvol;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *supvol;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *rechvol;
  GtkWidget *image4;
  GtkWidget *refvol;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *label2;

  espace_vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_vol), _("espace_vol"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace_vol), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 128, 56);
  gtk_widget_set_size_request (treeview1, 550, 350);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 360, 440);
  gtk_widget_set_size_request (combobox1, 160, 50);

  ajvol = gtk_button_new ();
  gtk_widget_show (ajvol);
  gtk_fixed_put (GTK_FIXED (fixed1), ajvol, 16, 256);
  gtk_widget_set_size_request (ajvol, 100, 50);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajvol), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  modvol = gtk_button_new ();
  gtk_widget_show (modvol);
  gtk_fixed_put (GTK_FIXED (fixed1), modvol, 88, 440);
  gtk_widget_set_size_request (modvol, 100, 50);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (modvol), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  supvol = gtk_button_new ();
  gtk_widget_show (supvol);
  gtk_fixed_put (GTK_FIXED (fixed1), supvol, 232, 440);
  gtk_widget_set_size_request (supvol, 100, 50);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (supvol), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  rechvol = gtk_button_new ();
  gtk_widget_show (rechvol);
  gtk_fixed_put (GTK_FIXED (fixed1), rechvol, 520, 440);
  gtk_widget_set_size_request (rechvol, 30, 50);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (rechvol), image4);

  refvol = gtk_button_new ();
  gtk_widget_show (refvol);
  gtk_fixed_put (GTK_FIXED (fixed1), refvol, 32, 104);
  gtk_widget_set_size_request (refvol, 30, 30);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (refvol), image1);

  label1 = gtk_label_new (_("Liste des voles"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 304, 24);
  gtk_widget_set_size_request (label1, 200, 20);

  label2 = gtk_label_new (_("Selecter un cin"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 368, 424);
  gtk_widget_set_size_request (label2, 128, 16);

  g_signal_connect ((gpointer) ajvol, "clicked",
                    G_CALLBACK (on_ajvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) modvol, "clicked",
                    G_CALLBACK (on_modvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) supvol, "clicked",
                    G_CALLBACK (on_supvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechvol, "clicked",
                    G_CALLBACK (on_rechvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) refvol, "clicked",
                    G_CALLBACK (on_refvol_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_vol, espace_vol, "espace_vol");
  GLADE_HOOKUP_OBJECT (espace_vol, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_vol, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (espace_vol, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (espace_vol, ajvol, "ajvol");
  GLADE_HOOKUP_OBJECT (espace_vol, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (espace_vol, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (espace_vol, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace_vol, label5, "label5");
  GLADE_HOOKUP_OBJECT (espace_vol, modvol, "modvol");
  GLADE_HOOKUP_OBJECT (espace_vol, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espace_vol, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espace_vol, image2, "image2");
  GLADE_HOOKUP_OBJECT (espace_vol, label3, "label3");
  GLADE_HOOKUP_OBJECT (espace_vol, supvol, "supvol");
  GLADE_HOOKUP_OBJECT (espace_vol, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espace_vol, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espace_vol, image3, "image3");
  GLADE_HOOKUP_OBJECT (espace_vol, label4, "label4");
  GLADE_HOOKUP_OBJECT (espace_vol, rechvol, "rechvol");
  GLADE_HOOKUP_OBJECT (espace_vol, image4, "image4");
  GLADE_HOOKUP_OBJECT (espace_vol, refvol, "refvol");
  GLADE_HOOKUP_OBJECT (espace_vol, image1, "image1");
  GLADE_HOOKUP_OBJECT (espace_vol, label1, "label1");
  GLADE_HOOKUP_OBJECT (espace_vol, label2, "label2");

  return espace_vol;
}

GtkWidget*
create_ajout_vol (void)
{
  GtkWidget *ajout_vol;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *label6;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label14;
  GtkWidget *entry7;
  GtkWidget *engvol;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *label9;
  GtkWidget *label8;
  GtkWidget *label15;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label10;
  GtkWidget *retesvol;
  GtkWidget *image6;

  ajout_vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_vol), _("ajout_vol"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout_vol), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 544, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 168, 96);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 168, 16);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 552, 104);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label6 = gtk_label_new ("");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 360, 240);
  gtk_widget_set_size_request (label6, 280, 33);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 168, 56);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label14 = gtk_label_new ("");
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 80, 184);
  gtk_widget_set_size_request (label14, 288, 40);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 544, 16);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  engvol = gtk_button_new ();
  gtk_widget_show (engvol);
  gtk_fixed_put (GTK_FIXED (fixed2), engvol, 168, 232);
  gtk_widget_set_size_request (engvol, 150, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (engvol), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox4), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  label9 = gtk_label_new (_("Nombre des  places"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 8, 56);
  gtk_widget_set_size_request (label9, 150, 27);

  label8 = gtk_label_new (_("R\303\251f\303\251rence"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 16, 16);
  gtk_widget_set_size_request (label8, 150, 27);

  label15 = gtk_label_new (_("Confirme votre r\303\251f\303\251rence"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 344, 8);
  gtk_widget_set_size_request (label15, 208, 40);

  label13 = gtk_label_new (_("Prix"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 440, 56);
  gtk_widget_set_size_request (label13, 150, 27);

  label12 = gtk_label_new (_("Destination"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 424, 104);
  gtk_widget_set_size_request (label12, 150, 27);

  label10 = gtk_label_new (_("Date (aller ==>retour)"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 8, 96);
  gtk_widget_set_size_request (label10, 150, 27);

  retesvol = gtk_button_new ();
  gtk_widget_show (retesvol);
  gtk_fixed_put (GTK_FIXED (fixed2), retesvol, 656, 240);
  gtk_widget_set_size_request (retesvol, 30, 30);

  image6 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (retesvol), image6);

  g_signal_connect ((gpointer) engvol, "clicked",
                    G_CALLBACK (on_engvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) retesvol, "clicked",
                    G_CALLBACK (on_retesvol_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_vol, ajout_vol, "ajout_vol");
  GLADE_HOOKUP_OBJECT (ajout_vol, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout_vol, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (ajout_vol, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajout_vol, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajout_vol, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (ajout_vol, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajout_vol, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajout_vol, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajout_vol, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajout_vol, engvol, "engvol");
  GLADE_HOOKUP_OBJECT (ajout_vol, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajout_vol, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajout_vol, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajout_vol, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajout_vol, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajout_vol, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajout_vol, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajout_vol, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajout_vol, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajout_vol, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajout_vol, retesvol, "retesvol");
  GLADE_HOOKUP_OBJECT (ajout_vol, image6, "image6");

  return ajout_vol;
}

GtkWidget*
create_modif_vol (void)
{
  GtkWidget *modif_vol;
  GtkWidget *fixed3;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *label22;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *label20;
  GtkWidget *save;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label23;
  GtkWidget *label24;

  modif_vol = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif_vol), _("modif_vol"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modif_vol), fixed3);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 152, 32);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry8), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9, 512, 120);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 152, 80);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed3), entry10, 512, 80);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed3), entry11, 152, 120);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed3), entry12, 512, 32);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label22 = gtk_label_new ("");
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 360, 224);
  gtk_widget_set_size_request (label22, 193, 41);

  label18 = gtk_label_new (_("Nombre des places"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 0, 80);
  gtk_widget_set_size_request (label18, 144, 24);

  label16 = gtk_label_new (_("R\303\251f\303\251rence"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 48, 32);
  gtk_widget_set_size_request (label16, 104, 32);

  label21 = gtk_label_new (_("Confirmation r\303\251f\303\251rence"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 320, 32);
  gtk_widget_set_size_request (label21, 176, 32);

  label19 = gtk_label_new (_("Prix"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 448, 88);
  gtk_widget_set_size_request (label19, 49, 17);

  label17 = gtk_label_new (_("Destination"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 392, 128);
  gtk_widget_set_size_request (label17, 112, 16);

  label20 = gtk_label_new (_("Date (aller/ retour)"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 8, 120);
  gtk_widget_set_size_request (label20, 152, 32);

  save = gtk_button_new ();
  gtk_widget_show (save);
  gtk_fixed_put (GTK_FIXED (fixed3), save, 320, 192);
  gtk_widget_set_size_request (save, 68, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (save), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("save"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox5), label23, FALSE, FALSE, 0);

  label24 = gtk_label_new (_("Modifier une vol :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 80, 8);
  gtk_widget_set_size_request (label24, 160, 17);

  g_signal_connect ((gpointer) modif_vol, "show",
                    G_CALLBACK (on_modif_vol_show),
                    NULL);
  g_signal_connect ((gpointer) save, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_vol, modif_vol, "modif_vol");
  GLADE_HOOKUP_OBJECT (modif_vol, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modif_vol, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modif_vol, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (modif_vol, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (modif_vol, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (modif_vol, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (modif_vol, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (modif_vol, label22, "label22");
  GLADE_HOOKUP_OBJECT (modif_vol, label18, "label18");
  GLADE_HOOKUP_OBJECT (modif_vol, label16, "label16");
  GLADE_HOOKUP_OBJECT (modif_vol, label21, "label21");
  GLADE_HOOKUP_OBJECT (modif_vol, label19, "label19");
  GLADE_HOOKUP_OBJECT (modif_vol, label17, "label17");
  GLADE_HOOKUP_OBJECT (modif_vol, label20, "label20");
  GLADE_HOOKUP_OBJECT (modif_vol, save, "save");
  GLADE_HOOKUP_OBJECT (modif_vol, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modif_vol, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modif_vol, image8, "image8");
  GLADE_HOOKUP_OBJECT (modif_vol, label23, "label23");
  GLADE_HOOKUP_OBJECT (modif_vol, label24, "label24");

  return modif_vol;
}

