/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_welcome (void);
GtkWidget* create_espace_agent (void);
GtkWidget* create_espace_admin (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_ajout_ag (void);
GtkWidget* create_modif_ag (void);
GtkWidget* create_validation (void);
GtkWidget* create_ajout_cl (void);
