/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_welcome (void)
{
  GtkWidget *welcome;
  GtkWidget *notebook1;
  GtkWidget *fixed9;
  GtkWidget *image17;
  GtkWidget *label69;
  GtkWidget *label33;
  GtkWidget *fixed10;
  GtkWidget *label34;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label5;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *hlogin;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image14;
  GtkWidget *label42;
  GtkWidget *login;
  GtkWidget *fixed4;
  GtkWidget *entry006;
  GtkWidget *entry004;
  GtkWidget *entry002;
  GtkWidget *entry003;
  GtkWidget *entry001;
  GtkWidget *entry005;
  GtkWidget *label35;
  GtkWidget *label3;
  GtkWidget *label39;
  GtkWidget *label36;
  GtkWidget *entry007;
  GtkWidget *entry008;
  GtkWidget *label40;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *label4;
  GtkWidget *button2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image13;
  GtkWidget *label41;
  GtkWidget *label00;
  GtkWidget *inscription;

  welcome = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (welcome), _("welcome"));
  gtk_window_set_position (GTK_WINDOW (welcome), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (welcome), 800, 400);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (welcome), notebook1);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  image17 = create_pixmap (welcome, "index.jpeg");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed9), image17, 0, 80);
  gtk_widget_set_size_request (image17, 712, 200);

  label69 = gtk_label_new_with_mnemonic (_("bienvenue dans notre agence de voyage "));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed9), label69, 0, 24);
  gtk_widget_set_size_request (label69, 704, 49);
  gtk_label_set_use_markup (GTK_LABEL (label69), TRUE);
  gtk_label_set_justify (GTK_LABEL (label69), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label69), TRUE);
  gtk_label_set_ellipsize (GTK_LABEL (label69), PANGO_ELLIPSIZE_MIDDLE);
  gtk_label_set_width_chars (GTK_LABEL (label69), 11);

  label33 = gtk_label_new (_("Welcome"));
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label33);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  label34 = gtk_label_new (_("liste des offres"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label34);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 296, 88);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 296, 136);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label5 = gtk_label_new ("");
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 160, 192);
  gtk_widget_set_size_request (label5, 41, 17);

  label2 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 144, 136);
  gtk_widget_set_size_request (label2, 150, 27);

  label1 = gtk_label_new (_("identifiant(cin)"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 144, 88);
  gtk_widget_set_size_request (label1, 150, 27);

  hlogin = gtk_button_new ();
  gtk_widget_show (hlogin);
  gtk_fixed_put (GTK_FIXED (fixed2), hlogin, 296, 200);
  gtk_widget_set_size_request (hlogin, 150, 50);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (hlogin), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image14 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox8), image14, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("            login                "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox8), label42, FALSE, FALSE, 0);

  login = gtk_label_new (_("login"));
  gtk_widget_show (login);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), login);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry006 = gtk_entry_new ();
  gtk_widget_show (entry006);
  gtk_fixed_put (GTK_FIXED (fixed4), entry006, 544, 56);
  gtk_widget_set_size_request (entry006, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry006), 8226);

  entry004 = gtk_entry_new ();
  gtk_widget_show (entry004);
  gtk_fixed_put (GTK_FIXED (fixed4), entry004, 168, 136);
  gtk_widget_set_size_request (entry004, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry004), 8226);

  entry002 = gtk_entry_new ();
  gtk_widget_show (entry002);
  gtk_fixed_put (GTK_FIXED (fixed4), entry002, 168, 56);
  gtk_widget_set_size_request (entry002, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry002), 8226);

  entry003 = gtk_entry_new ();
  gtk_widget_show (entry003);
  gtk_fixed_put (GTK_FIXED (fixed4), entry003, 168, 96);
  gtk_widget_set_size_request (entry003, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry003), 8226);

  entry001 = gtk_entry_new ();
  gtk_widget_show (entry001);
  gtk_fixed_put (GTK_FIXED (fixed4), entry001, 168, 16);
  gtk_widget_set_size_request (entry001, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry001), 8226);

  entry005 = gtk_entry_new ();
  gtk_widget_show (entry005);
  gtk_fixed_put (GTK_FIXED (fixed4), entry005, 544, 16);
  gtk_widget_set_size_request (entry005, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry005), 8226);

  label35 = gtk_label_new (_("prenom"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 16, 56);
  gtk_widget_set_size_request (label35, 150, 27);

  label3 = gtk_label_new (_("nom"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed4), label3, 16, 16);
  gtk_widget_set_size_request (label3, 150, 27);

  label39 = gtk_label_new (_("adresse"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed4), label39, 392, 16);
  gtk_widget_set_size_request (label39, 150, 27);

  label36 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 392, 56);
  gtk_widget_set_size_request (label36, 150, 27);

  entry007 = gtk_entry_new ();
  gtk_widget_show (entry007);
  gtk_fixed_put (GTK_FIXED (fixed4), entry007, 544, 96);
  gtk_widget_set_size_request (entry007, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry007), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry007), 8226);

  entry008 = gtk_entry_new ();
  gtk_widget_show (entry008);
  gtk_fixed_put (GTK_FIXED (fixed4), entry008, 544, 136);
  gtk_widget_set_size_request (entry008, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry008), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry008), 8226);

  label40 = gtk_label_new (_("confirmer mot de passe"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed4), label40, 368, 136);
  gtk_widget_set_size_request (label40, 174, 27);

  label38 = gtk_label_new (_("cin"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed4), label38, 16, 96);
  gtk_widget_set_size_request (label38, 150, 27);

  label37 = gtk_label_new (_("GSM"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 16, 136);
  gtk_widget_set_size_request (label37, 150, 27);

  label4 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed4), label4, 392, 96);
  gtk_widget_set_size_request (label4, 150, 27);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 168, 232);
  gtk_widget_set_size_request (button2, 150, 50);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox7), image13, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox7), label41, FALSE, FALSE, 0);

  label00 = gtk_label_new ("");
  gtk_widget_show (label00);
  gtk_fixed_put (GTK_FIXED (fixed4), label00, 352, 240);
  gtk_widget_set_size_request (label00, 280, 33);

  inscription = gtk_label_new (_("inscription"));
  gtk_widget_show (inscription);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), inscription);

  g_signal_connect ((gpointer) hlogin, "clicked",
                    G_CALLBACK (on_login1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (welcome, welcome, "welcome");
  GLADE_HOOKUP_OBJECT (welcome, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (welcome, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (welcome, image17, "image17");
  GLADE_HOOKUP_OBJECT (welcome, label69, "label69");
  GLADE_HOOKUP_OBJECT (welcome, label33, "label33");
  GLADE_HOOKUP_OBJECT (welcome, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (welcome, label34, "label34");
  GLADE_HOOKUP_OBJECT (welcome, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (welcome, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (welcome, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (welcome, label5, "label5");
  GLADE_HOOKUP_OBJECT (welcome, label2, "label2");
  GLADE_HOOKUP_OBJECT (welcome, label1, "label1");
  GLADE_HOOKUP_OBJECT (welcome, hlogin, "hlogin");
  GLADE_HOOKUP_OBJECT (welcome, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (welcome, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (welcome, image14, "image14");
  GLADE_HOOKUP_OBJECT (welcome, label42, "label42");
  GLADE_HOOKUP_OBJECT (welcome, login, "login");
  GLADE_HOOKUP_OBJECT (welcome, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (welcome, entry006, "entry006");
  GLADE_HOOKUP_OBJECT (welcome, entry004, "entry004");
  GLADE_HOOKUP_OBJECT (welcome, entry002, "entry002");
  GLADE_HOOKUP_OBJECT (welcome, entry003, "entry003");
  GLADE_HOOKUP_OBJECT (welcome, entry001, "entry001");
  GLADE_HOOKUP_OBJECT (welcome, entry005, "entry005");
  GLADE_HOOKUP_OBJECT (welcome, label35, "label35");
  GLADE_HOOKUP_OBJECT (welcome, label3, "label3");
  GLADE_HOOKUP_OBJECT (welcome, label39, "label39");
  GLADE_HOOKUP_OBJECT (welcome, label36, "label36");
  GLADE_HOOKUP_OBJECT (welcome, entry007, "entry007");
  GLADE_HOOKUP_OBJECT (welcome, entry008, "entry008");
  GLADE_HOOKUP_OBJECT (welcome, label40, "label40");
  GLADE_HOOKUP_OBJECT (welcome, label38, "label38");
  GLADE_HOOKUP_OBJECT (welcome, label37, "label37");
  GLADE_HOOKUP_OBJECT (welcome, label4, "label4");
  GLADE_HOOKUP_OBJECT (welcome, button2, "button2");
  GLADE_HOOKUP_OBJECT (welcome, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (welcome, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (welcome, image13, "image13");
  GLADE_HOOKUP_OBJECT (welcome, label41, "label41");
  GLADE_HOOKUP_OBJECT (welcome, label00, "label00");
  GLADE_HOOKUP_OBJECT (welcome, inscription, "inscription");

  return welcome;
}

GtkWidget*
create_espace_agent (void)
{
  GtkWidget *espace_agent;
  GtkWidget *notebook2;
  GtkWidget *empty_notebook_page;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;

  espace_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_agent), _("espace_agent"));
  gtk_window_set_position (GTK_WINDOW (espace_agent), GTK_WIN_POS_CENTER);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (espace_agent), notebook2);
  gtk_widget_set_size_request (notebook2, 700, 350);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label43 = gtk_label_new (_("label43"));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label43);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label44 = gtk_label_new (_("label44"));
  gtk_widget_show (label44);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label44);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label45 = gtk_label_new (_("label45"));
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label45);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_agent, espace_agent, "espace_agent");
  GLADE_HOOKUP_OBJECT (espace_agent, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (espace_agent, label43, "label43");
  GLADE_HOOKUP_OBJECT (espace_agent, label44, "label44");
  GLADE_HOOKUP_OBJECT (espace_agent, label45, "label45");

  return espace_agent;
}

GtkWidget*
create_espace_admin (void)
{
  GtkWidget *espace_admin;
  GtkWidget *notebook4;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *refresh;
  GtkWidget *image7;
  GtkWidget *_;
  GtkWidget *label20;
  GtkWidget *combobox1;
  GtkWidget *r_cin;
  GtkWidget *image10;
  GtkWidget *modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *button5;
  GtkWidget *image8;
  GtkWidget *ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *label70;
  GtkWidget *fixed15;
  GtkWidget *treeview2;
  GtkWidget *combobox2;
  GtkWidget *button11;
  GtkWidget *image24;
  GtkWidget *label75;
  GtkWidget *label77;
  GtkWidget *modifier_cl;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image23;
  GtkWidget *label78;
  GtkWidget *supprimer_cl;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image19;
  GtkWidget *label74;
  GtkWidget *r_cin_cl;
  GtkWidget *image22;
  GtkWidget *refresh_cl;
  GtkWidget *image20;
  GtkWidget *ajouter_cl1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image21;
  GtkWidget *label76;
  GtkWidget *label73;
  GtkWidget *fixed13;
  GtkWidget *label71;

  espace_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (espace_admin, 700, 600);
  gtk_window_set_title (GTK_WINDOW (espace_admin), _("espace_admin"));
  gtk_window_set_position (GTK_WINDOW (espace_admin), GTK_WIN_POS_CENTER);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (espace_admin), notebook4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 128, 56);
  gtk_widget_set_size_request (treeview1, 550, 350);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), supprimer, 232, 440);
  gtk_widget_set_size_request (supprimer, 100, 50);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  refresh = gtk_button_new ();
  gtk_widget_show (refresh);
  gtk_fixed_put (GTK_FIXED (fixed5), refresh, 32, 104);
  gtk_widget_set_size_request (refresh, 30, 30);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (refresh), image7);

  _ = gtk_label_new (_("liste des agents"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed5), _, 304, 24);
  gtk_widget_set_size_request (_, 200, 20);

  label20 = gtk_label_new (_("selecter un cin"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 368, 424);
  gtk_widget_set_size_request (label20, 128, 16);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1, 360, 440);
  gtk_widget_set_size_request (combobox1, 160, 50);

  r_cin = gtk_button_new ();
  gtk_widget_show (r_cin);
  gtk_fixed_put (GTK_FIXED (fixed5), r_cin, 520, 440);
  gtk_widget_set_size_request (r_cin, 30, 50);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (r_cin), image10);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier, 88, 440);
  gtk_widget_set_size_request (modifier, 100, 50);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed5), button5, 648, 456);
  gtk_widget_set_size_request (button5, 30, 30);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (button5), image8);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), ajouter, 16, 256);
  gtk_widget_set_size_request (ajouter, 100, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  label70 = gtk_label_new (_("gestion des agents"));
  gtk_widget_show (label70);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label70);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed15);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview2, 128, 56);
  gtk_widget_set_size_request (treeview2, 550, 350);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed15), combobox2, 360, 440);
  gtk_widget_set_size_request (combobox2, 160, 50);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed15), button11, 648, 456);
  gtk_widget_set_size_request (button11, 30, 30);

  image24 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (button11), image24);

  label75 = gtk_label_new (_("liste des clients"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed15), label75, 304, 24);
  gtk_widget_set_size_request (label75, 200, 20);

  label77 = gtk_label_new (_("selecter un cin"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed15), label77, 368, 424);
  gtk_widget_set_size_request (label77, 128, 16);

  modifier_cl = gtk_button_new ();
  gtk_widget_show (modifier_cl);
  gtk_fixed_put (GTK_FIXED (fixed15), modifier_cl, 88, 440);
  gtk_widget_set_size_request (modifier_cl, 100, 50);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (modifier_cl), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image23 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox12), image23, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox12), label78, FALSE, FALSE, 0);

  supprimer_cl = gtk_button_new ();
  gtk_widget_show (supprimer_cl);
  gtk_fixed_put (GTK_FIXED (fixed15), supprimer_cl, 232, 440);
  gtk_widget_set_size_request (supprimer_cl, 100, 50);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (supprimer_cl), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image19 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox10), image19, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox10), label74, FALSE, FALSE, 0);

  r_cin_cl = gtk_button_new ();
  gtk_widget_show (r_cin_cl);
  gtk_fixed_put (GTK_FIXED (fixed15), r_cin_cl, 520, 440);
  gtk_widget_set_size_request (r_cin_cl, 30, 50);

  image22 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (r_cin_cl), image22);

  refresh_cl = gtk_button_new ();
  gtk_widget_show (refresh_cl);
  gtk_fixed_put (GTK_FIXED (fixed15), refresh_cl, 32, 104);
  gtk_widget_set_size_request (refresh_cl, 30, 30);

  image20 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (refresh_cl), image20);

  ajouter_cl1 = gtk_button_new ();
  gtk_widget_show (ajouter_cl1);
  gtk_fixed_put (GTK_FIXED (fixed15), ajouter_cl1, 16, 256);
  gtk_widget_set_size_request (ajouter_cl1, 100, 50);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (ajouter_cl1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox11), image21, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox11), label76, FALSE, FALSE, 0);

  label73 = gtk_label_new (_("gestion des clients"));
  gtk_widget_show (label73);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label73);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed13);

  label71 = gtk_label_new (_("reclamation"));
  gtk_widget_show (label71);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label71);

  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh, "clicked",
                    G_CALLBACK (on_refresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) r_cin, "clicked",
                    G_CALLBACK (on_r_cin_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_cl, "clicked",
                    G_CALLBACK (on_modifier_cl_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_cl, "clicked",
                    G_CALLBACK (on_supprimer_cl_clicked),
                    NULL);
  g_signal_connect ((gpointer) r_cin_cl, "clicked",
                    G_CALLBACK (on_r_cin_cl_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_cl, "clicked",
                    G_CALLBACK (on_refresh_cl_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_cl1, "clicked",
                    G_CALLBACK (on_ajouter_cl1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_admin, espace_admin, "espace_admin");
  GLADE_HOOKUP_OBJECT (espace_admin, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (espace_admin, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (espace_admin, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (espace_admin, image3, "image3");
  GLADE_HOOKUP_OBJECT (espace_admin, label8, "label8");
  GLADE_HOOKUP_OBJECT (espace_admin, refresh, "refresh");
  GLADE_HOOKUP_OBJECT (espace_admin, image7, "image7");
  GLADE_HOOKUP_OBJECT (espace_admin, _, "_");
  GLADE_HOOKUP_OBJECT (espace_admin, label20, "label20");
  GLADE_HOOKUP_OBJECT (espace_admin, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (espace_admin, r_cin, "r_cin");
  GLADE_HOOKUP_OBJECT (espace_admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (espace_admin, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espace_admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (espace_admin, label7, "label7");
  GLADE_HOOKUP_OBJECT (espace_admin, button5, "button5");
  GLADE_HOOKUP_OBJECT (espace_admin, image8, "image8");
  GLADE_HOOKUP_OBJECT (espace_admin, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (espace_admin, image4, "image4");
  GLADE_HOOKUP_OBJECT (espace_admin, label10, "label10");
  GLADE_HOOKUP_OBJECT (espace_admin, label70, "label70");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (espace_admin, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (espace_admin, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (espace_admin, button11, "button11");
  GLADE_HOOKUP_OBJECT (espace_admin, image24, "image24");
  GLADE_HOOKUP_OBJECT (espace_admin, label75, "label75");
  GLADE_HOOKUP_OBJECT (espace_admin, label77, "label77");
  GLADE_HOOKUP_OBJECT (espace_admin, modifier_cl, "modifier_cl");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (espace_admin, image23, "image23");
  GLADE_HOOKUP_OBJECT (espace_admin, label78, "label78");
  GLADE_HOOKUP_OBJECT (espace_admin, supprimer_cl, "supprimer_cl");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (espace_admin, image19, "image19");
  GLADE_HOOKUP_OBJECT (espace_admin, label74, "label74");
  GLADE_HOOKUP_OBJECT (espace_admin, r_cin_cl, "r_cin_cl");
  GLADE_HOOKUP_OBJECT (espace_admin, image22, "image22");
  GLADE_HOOKUP_OBJECT (espace_admin, refresh_cl, "refresh_cl");
  GLADE_HOOKUP_OBJECT (espace_admin, image20, "image20");
  GLADE_HOOKUP_OBJECT (espace_admin, ajouter_cl1, "ajouter_cl1");
  GLADE_HOOKUP_OBJECT (espace_admin, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (espace_admin, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (espace_admin, image21, "image21");
  GLADE_HOOKUP_OBJECT (espace_admin, label76, "label76");
  GLADE_HOOKUP_OBJECT (espace_admin, label73, "label73");
  GLADE_HOOKUP_OBJECT (espace_admin, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (espace_admin, label71, "label71");

  return espace_admin;
}

GtkWidget*
create_espace_client (void)
{
  GtkWidget *espace_client;
  GtkWidget *notebook3;
  GtkWidget *fixed19;
  GtkWidget *treeview100;
  GtkWidget *label46;
  GtkWidget *fixed17;
  GtkWidget *entry101;
  GtkObject *spinbutton101_adj;
  GtkWidget *spinbutton101;
  GtkWidget *entry102;
  GtkWidget *combobox102;
  GtkWidget *combobox101;
  GtkWidget *reserver;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image27;
  GtkWidget *label93;
  GtkWidget *label106;
  GtkWidget *label105;
  GtkWidget *label104;
  GtkWidget *label103;
  GtkWidget *label102;
  GtkWidget *label101;
  GtkWidget *label47;
  GtkWidget *fixed18;
  GtkObject *spinbutton201_adj;
  GtkWidget *spinbutton201;
  GtkObject *spinbutton203_adj;
  GtkWidget *spinbutton203;
  GtkObject *spinbutton202_adj;
  GtkWidget *spinbutton202;
  GtkObject *spinbutton204_adj;
  GtkWidget *spinbutton204;
  GtkWidget *combobox202;
  GtkWidget *entry201;
  GtkWidget *label202;
  GtkWidget *label203;
  GtkWidget *label204;
  GtkWidget *label205;
  GtkWidget *label201;
  GtkWidget *label206;
  GtkWidget *label207;
  GtkWidget *label208;
  GtkWidget *label209;
  GtkWidget *combobox201;
  GtkWidget *button201;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image28;
  GtkWidget *label115;
  GtkWidget *label48;

  espace_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_client), _("espace_client"));
  gtk_window_set_position (GTK_WINDOW (espace_client), GTK_WIN_POS_CENTER);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (espace_client), notebook3);
  gtk_widget_set_size_request (notebook3, 700, 350);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed19);

  treeview100 = gtk_tree_view_new ();
  gtk_widget_show (treeview100);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview100, 64, 40);
  gtk_widget_set_size_request (treeview100, 300, 200);

  label46 = gtk_label_new (_("label46"));
  gtk_widget_show (label46);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label46);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed17);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed17), entry101, 640, 96);
  gtk_widget_set_size_request (entry101, 40, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry101), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  spinbutton101_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton101 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton101_adj), 1, 0);
  gtk_widget_show (spinbutton101);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton101, 152, 144);
  gtk_widget_set_size_request (spinbutton101, 60, 27);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed17), entry102, 352, 144);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry102), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  combobox102 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox102);
  gtk_fixed_put (GTK_FIXED (fixed17), combobox102, 136, 88);
  gtk_widget_set_size_request (combobox102, 264, 31);

  combobox101 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox101);
  gtk_fixed_put (GTK_FIXED (fixed17), combobox101, 136, 24);
  gtk_widget_set_size_request (combobox101, 128, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("france"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("usa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("rome"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox101), _("russia"));

  reserver = gtk_button_new ();
  gtk_widget_show (reserver);
  gtk_fixed_put (GTK_FIXED (fixed17), reserver, 200, 216);
  gtk_widget_set_size_request (reserver, 104, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (reserver), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image27 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox14), image27, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("reserver"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox14), label93, FALSE, FALSE, 0);

  label106 = gtk_label_new ("");
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed17), label106, 368, 192);
  gtk_widget_set_size_request (label106, 241, 33);

  label105 = gtk_label_new (_("prix(dt)"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed17), label105, 288, 152);
  gtk_widget_set_size_request (label105, 64, 17);

  label104 = gtk_label_new (_("nombre des places"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed17), label104, 8, 152);
  gtk_widget_set_size_request (label104, 144, 16);

  label103 = gtk_label_new (_("nombre des places disponibles"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed17), label103, 408, 104);
  gtk_widget_set_size_request (label103, 224, 16);

  label102 = gtk_label_new (_("vols disponibles"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed17), label102, 8, 96);
  gtk_widget_set_size_request (label102, 128, 17);

  label101 = gtk_label_new (_("destination"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed17), label101, 24, 32);
  gtk_widget_set_size_request (label101, 96, 17);

  label47 = gtk_label_new (_("reservation vol"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label47);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed18);

  spinbutton201_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton201 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton201_adj), 1, 0);
  gtk_widget_show (spinbutton201);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton201, 208, 24);
  gtk_widget_set_size_request (spinbutton201, 60, 27);

  spinbutton203_adj = gtk_adjustment_new (2019, 2019, 2050, 1, 10, 10);
  spinbutton203 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton203_adj), 1, 0);
  gtk_widget_show (spinbutton203);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton203, 488, 24);
  gtk_widget_set_size_request (spinbutton203, 60, 27);

  spinbutton202_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton202 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton202_adj), 1, 0);
  gtk_widget_show (spinbutton202);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton202, 328, 24);
  gtk_widget_set_size_request (spinbutton202, 60, 27);

  spinbutton204_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton204 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton204_adj), 1, 0);
  gtk_widget_show (spinbutton204);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton204, 104, 184);
  gtk_widget_set_size_request (spinbutton204, 60, 27);

  combobox202 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox202);
  gtk_fixed_put (GTK_FIXED (fixed18), combobox202, 168, 136);
  gtk_widget_set_size_request (combobox202, 184, 31);

  entry201 = gtk_entry_new ();
  gtk_widget_show (entry201);
  gtk_fixed_put (GTK_FIXED (fixed18), entry201, 384, 184);
  gtk_widget_set_size_request (entry201, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry201), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry201), 8226);

  label202 = gtk_label_new (_("date de r\303\250servation:"));
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed18), label202, 0, 32);
  gtk_widget_set_size_request (label202, 152, 17);

  label203 = gtk_label_new (_("jour"));
  gtk_widget_show (label203);
  gtk_fixed_put (GTK_FIXED (fixed18), label203, 168, 33);
  gtk_widget_set_size_request (label203, 48, 16);

  label204 = gtk_label_new (_("mois"));
  gtk_widget_show (label204);
  gtk_fixed_put (GTK_FIXED (fixed18), label204, 272, 32);
  gtk_widget_set_size_request (label204, 48, 16);

  label205 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label205);
  gtk_fixed_put (GTK_FIXED (fixed18), label205, 424, 32);
  gtk_widget_set_size_request (label205, 48, 16);

  label201 = gtk_label_new (_("marque"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed18), label201, 72, 88);
  gtk_widget_set_size_request (label201, 57, 17);

  label206 = gtk_label_new (_("voitures disponibles"));
  gtk_widget_show (label206);
  gtk_fixed_put (GTK_FIXED (fixed18), label206, 8, 144);
  gtk_widget_set_size_request (label206, 152, 17);

  label207 = gtk_label_new (_("dur\303\251e"));
  gtk_widget_show (label207);
  gtk_fixed_put (GTK_FIXED (fixed18), label207, 48, 192);
  gtk_widget_set_size_request (label207, 56, 16);

  label208 = gtk_label_new (_("prix(dt)"));
  gtk_widget_show (label208);
  gtk_fixed_put (GTK_FIXED (fixed18), label208, 312, 192);
  gtk_widget_set_size_request (label208, 70, 17);

  label209 = gtk_label_new ("");
  gtk_widget_show (label209);
  gtk_fixed_put (GTK_FIXED (fixed18), label209, 152, 224);
  gtk_widget_set_size_request (label209, 273, 16);

  combobox201 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox201);
  gtk_fixed_put (GTK_FIXED (fixed18), combobox201, 168, 80);
  gtk_widget_set_size_request (combobox201, 184, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("bmw"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("tesla"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("land_rover"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("bugatti"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("lamborghini"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox201), _("mercedes"));

  button201 = gtk_button_new ();
  gtk_widget_show (button201);
  gtk_fixed_put (GTK_FIXED (fixed18), button201, 240, 248);
  gtk_widget_set_size_request (button201, 104, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button201), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image28 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox15), image28, FALSE, FALSE, 0);

  label115 = gtk_label_new_with_mnemonic (_("reserver"));
  gtk_widget_show (label115);
  gtk_box_pack_start (GTK_BOX (hbox15), label115, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("reservation voiture"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label48);

  g_signal_connect ((gpointer) spinbutton101, "changed",
                    G_CALLBACK (on_spinbutton101_changed),
                    NULL);
  g_signal_connect ((gpointer) combobox102, "changed",
                    G_CALLBACK (on_combobox102_changed),
                    NULL);
  g_signal_connect ((gpointer) combobox101, "changed",
                    G_CALLBACK (on_combobox101_changed),
                    NULL);
  g_signal_connect ((gpointer) reserver, "clicked",
                    G_CALLBACK (on_reserver_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton204, "changed",
                    G_CALLBACK (on_spinbutton204_changed),
                    NULL);
  g_signal_connect ((gpointer) combobox201, "changed",
                    G_CALLBACK (on_combobox201_changed),
                    NULL);
  g_signal_connect ((gpointer) button201, "clicked",
                    G_CALLBACK (on_button201_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_client, espace_client, "espace_client");
  GLADE_HOOKUP_OBJECT (espace_client, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (espace_client, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (espace_client, treeview100, "treeview100");
  GLADE_HOOKUP_OBJECT (espace_client, label46, "label46");
  GLADE_HOOKUP_OBJECT (espace_client, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (espace_client, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (espace_client, spinbutton101, "spinbutton101");
  GLADE_HOOKUP_OBJECT (espace_client, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (espace_client, combobox102, "combobox102");
  GLADE_HOOKUP_OBJECT (espace_client, combobox101, "combobox101");
  GLADE_HOOKUP_OBJECT (espace_client, reserver, "reserver");
  GLADE_HOOKUP_OBJECT (espace_client, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (espace_client, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (espace_client, image27, "image27");
  GLADE_HOOKUP_OBJECT (espace_client, label93, "label93");
  GLADE_HOOKUP_OBJECT (espace_client, label106, "label106");
  GLADE_HOOKUP_OBJECT (espace_client, label105, "label105");
  GLADE_HOOKUP_OBJECT (espace_client, label104, "label104");
  GLADE_HOOKUP_OBJECT (espace_client, label103, "label103");
  GLADE_HOOKUP_OBJECT (espace_client, label102, "label102");
  GLADE_HOOKUP_OBJECT (espace_client, label101, "label101");
  GLADE_HOOKUP_OBJECT (espace_client, label47, "label47");
  GLADE_HOOKUP_OBJECT (espace_client, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (espace_client, spinbutton201, "spinbutton201");
  GLADE_HOOKUP_OBJECT (espace_client, spinbutton203, "spinbutton203");
  GLADE_HOOKUP_OBJECT (espace_client, spinbutton202, "spinbutton202");
  GLADE_HOOKUP_OBJECT (espace_client, spinbutton204, "spinbutton204");
  GLADE_HOOKUP_OBJECT (espace_client, combobox202, "combobox202");
  GLADE_HOOKUP_OBJECT (espace_client, entry201, "entry201");
  GLADE_HOOKUP_OBJECT (espace_client, label202, "label202");
  GLADE_HOOKUP_OBJECT (espace_client, label203, "label203");
  GLADE_HOOKUP_OBJECT (espace_client, label204, "label204");
  GLADE_HOOKUP_OBJECT (espace_client, label205, "label205");
  GLADE_HOOKUP_OBJECT (espace_client, label201, "label201");
  GLADE_HOOKUP_OBJECT (espace_client, label206, "label206");
  GLADE_HOOKUP_OBJECT (espace_client, label207, "label207");
  GLADE_HOOKUP_OBJECT (espace_client, label208, "label208");
  GLADE_HOOKUP_OBJECT (espace_client, label209, "label209");
  GLADE_HOOKUP_OBJECT (espace_client, combobox201, "combobox201");
  GLADE_HOOKUP_OBJECT (espace_client, button201, "button201");
  GLADE_HOOKUP_OBJECT (espace_client, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (espace_client, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (espace_client, image28, "image28");
  GLADE_HOOKUP_OBJECT (espace_client, label115, "label115");
  GLADE_HOOKUP_OBJECT (espace_client, label48, "label48");

  return espace_client;
}

GtkWidget*
create_ajout_ag (void)
{
  GtkWidget *ajout_ag;
  GtkWidget *fixed11;
  GtkWidget *entry016;
  GtkWidget *entry014;
  GtkWidget *entry012;
  GtkWidget *entry013;
  GtkWidget *entry011;
  GtkWidget *entry015;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *entry017;
  GtkWidget *entry018;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *retour_ag;
  GtkWidget *image16;
  GtkWidget *ajouter_ag;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label57;
  GtkWidget *label01;

  ajout_ag = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_ag), _("ajout"));
  gtk_window_set_position (GTK_WINDOW (ajout_ag), GTK_WIN_POS_CENTER);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (ajout_ag), fixed11);

  entry016 = gtk_entry_new ();
  gtk_widget_show (entry016);
  gtk_fixed_put (GTK_FIXED (fixed11), entry016, 544, 56);
  gtk_widget_set_size_request (entry016, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry016), 8226);

  entry014 = gtk_entry_new ();
  gtk_widget_show (entry014);
  gtk_fixed_put (GTK_FIXED (fixed11), entry014, 168, 136);
  gtk_widget_set_size_request (entry014, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry014), 8226);

  entry012 = gtk_entry_new ();
  gtk_widget_show (entry012);
  gtk_fixed_put (GTK_FIXED (fixed11), entry012, 168, 56);
  gtk_widget_set_size_request (entry012, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry012), 8226);

  entry013 = gtk_entry_new ();
  gtk_widget_show (entry013);
  gtk_fixed_put (GTK_FIXED (fixed11), entry013, 168, 96);
  gtk_widget_set_size_request (entry013, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry013), 8226);

  entry011 = gtk_entry_new ();
  gtk_widget_show (entry011);
  gtk_fixed_put (GTK_FIXED (fixed11), entry011, 168, 16);
  gtk_widget_set_size_request (entry011, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry011), 8226);

  entry015 = gtk_entry_new ();
  gtk_widget_show (entry015);
  gtk_fixed_put (GTK_FIXED (fixed11), entry015, 544, 16);
  gtk_widget_set_size_request (entry015, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry015), 8226);

  label49 = gtk_label_new (_("prenom"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed11), label49, 16, 56);
  gtk_widget_set_size_request (label49, 150, 27);

  label50 = gtk_label_new (_("nom"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed11), label50, 16, 16);
  gtk_widget_set_size_request (label50, 150, 27);

  label51 = gtk_label_new (_("adresse"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed11), label51, 392, 16);
  gtk_widget_set_size_request (label51, 150, 27);

  label52 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed11), label52, 392, 56);
  gtk_widget_set_size_request (label52, 150, 27);

  entry017 = gtk_entry_new ();
  gtk_widget_show (entry017);
  gtk_fixed_put (GTK_FIXED (fixed11), entry017, 544, 96);
  gtk_widget_set_size_request (entry017, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry017), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry017), 8226);

  entry018 = gtk_entry_new ();
  gtk_widget_show (entry018);
  gtk_fixed_put (GTK_FIXED (fixed11), entry018, 544, 136);
  gtk_widget_set_size_request (entry018, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry018), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry018), 8226);

  label53 = gtk_label_new (_("confirmer mot de passe"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed11), label53, 368, 136);
  gtk_widget_set_size_request (label53, 174, 27);

  label54 = gtk_label_new (_("cin"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed11), label54, 16, 96);
  gtk_widget_set_size_request (label54, 150, 27);

  label55 = gtk_label_new (_("GSM"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 16, 136);
  gtk_widget_set_size_request (label55, 150, 27);

  label56 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 392, 96);
  gtk_widget_set_size_request (label56, 150, 27);

  retour_ag = gtk_button_new ();
  gtk_widget_show (retour_ag);
  gtk_fixed_put (GTK_FIXED (fixed11), retour_ag, 664, 264);
  gtk_widget_set_size_request (retour_ag, 30, 30);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (retour_ag), image16);

  ajouter_ag = gtk_button_new ();
  gtk_widget_show (ajouter_ag);
  gtk_fixed_put (GTK_FIXED (fixed11), ajouter_ag, 168, 232);
  gtk_widget_set_size_request (ajouter_ag, 150, 50);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ajouter_ag), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox9), label57, FALSE, FALSE, 0);

  label01 = gtk_label_new ("");
  gtk_widget_show (label01);
  gtk_fixed_put (GTK_FIXED (fixed11), label01, 344, 240);
  gtk_widget_set_size_request (label01, 280, 33);

  g_signal_connect ((gpointer) retour_ag, "clicked",
                    G_CALLBACK (on_retour_ag_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_ag, "clicked",
                    G_CALLBACK (on_ajouter_ag_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_ag, ajout_ag, "ajout_ag");
  GLADE_HOOKUP_OBJECT (ajout_ag, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry016, "entry016");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry014, "entry014");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry012, "entry012");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry013, "entry013");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry011, "entry011");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry015, "entry015");
  GLADE_HOOKUP_OBJECT (ajout_ag, label49, "label49");
  GLADE_HOOKUP_OBJECT (ajout_ag, label50, "label50");
  GLADE_HOOKUP_OBJECT (ajout_ag, label51, "label51");
  GLADE_HOOKUP_OBJECT (ajout_ag, label52, "label52");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry017, "entry017");
  GLADE_HOOKUP_OBJECT (ajout_ag, entry018, "entry018");
  GLADE_HOOKUP_OBJECT (ajout_ag, label53, "label53");
  GLADE_HOOKUP_OBJECT (ajout_ag, label54, "label54");
  GLADE_HOOKUP_OBJECT (ajout_ag, label55, "label55");
  GLADE_HOOKUP_OBJECT (ajout_ag, label56, "label56");
  GLADE_HOOKUP_OBJECT (ajout_ag, retour_ag, "retour_ag");
  GLADE_HOOKUP_OBJECT (ajout_ag, image16, "image16");
  GLADE_HOOKUP_OBJECT (ajout_ag, ajouter_ag, "ajouter_ag");
  GLADE_HOOKUP_OBJECT (ajout_ag, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajout_ag, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajout_ag, image15, "image15");
  GLADE_HOOKUP_OBJECT (ajout_ag, label57, "label57");
  GLADE_HOOKUP_OBJECT (ajout_ag, label01, "label01");

  return ajout_ag;
}

GtkWidget*
create_modif_ag (void)
{
  GtkWidget *modif_ag;
  GtkWidget *fixed12;
  GtkWidget *entry026;
  GtkWidget *entry024;
  GtkWidget *entry022;
  GtkWidget *entry023;
  GtkWidget *entry021;
  GtkWidget *entry025;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *entry027;
  GtkWidget *entry028;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *retour_modif_ag;
  GtkWidget *image11;
  GtkWidget *save;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image12;
  GtkWidget *label27;
  GtkWidget *label02;

  modif_ag = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif_ag), _("modif"));
  gtk_window_set_position (GTK_WINDOW (modif_ag), GTK_WIN_POS_CENTER);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (modif_ag), fixed12);

  entry026 = gtk_entry_new ();
  gtk_widget_show (entry026);
  gtk_fixed_put (GTK_FIXED (fixed12), entry026, 544, 56);
  gtk_widget_set_size_request (entry026, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry026), 8226);

  entry024 = gtk_entry_new ();
  gtk_widget_show (entry024);
  gtk_fixed_put (GTK_FIXED (fixed12), entry024, 168, 136);
  gtk_widget_set_size_request (entry024, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry024), 8226);

  entry022 = gtk_entry_new ();
  gtk_widget_show (entry022);
  gtk_fixed_put (GTK_FIXED (fixed12), entry022, 168, 56);
  gtk_widget_set_size_request (entry022, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry022), 8226);

  entry023 = gtk_entry_new ();
  gtk_widget_show (entry023);
  gtk_fixed_put (GTK_FIXED (fixed12), entry023, 168, 96);
  gtk_widget_set_size_request (entry023, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry023), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry023), 8226);

  entry021 = gtk_entry_new ();
  gtk_widget_show (entry021);
  gtk_fixed_put (GTK_FIXED (fixed12), entry021, 168, 16);
  gtk_widget_set_size_request (entry021, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry021), 8226);

  entry025 = gtk_entry_new ();
  gtk_widget_show (entry025);
  gtk_fixed_put (GTK_FIXED (fixed12), entry025, 544, 16);
  gtk_widget_set_size_request (entry025, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry025), 8226);

  label58 = gtk_label_new (_("prenom"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed12), label58, 16, 56);
  gtk_widget_set_size_request (label58, 150, 27);

  label59 = gtk_label_new (_("nom"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed12), label59, 16, 16);
  gtk_widget_set_size_request (label59, 150, 27);

  label60 = gtk_label_new (_("adresse"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed12), label60, 392, 16);
  gtk_widget_set_size_request (label60, 150, 27);

  label61 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed12), label61, 392, 56);
  gtk_widget_set_size_request (label61, 150, 27);

  entry027 = gtk_entry_new ();
  gtk_widget_show (entry027);
  gtk_fixed_put (GTK_FIXED (fixed12), entry027, 544, 96);
  gtk_widget_set_size_request (entry027, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry027), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry027), 8226);

  entry028 = gtk_entry_new ();
  gtk_widget_show (entry028);
  gtk_fixed_put (GTK_FIXED (fixed12), entry028, 544, 136);
  gtk_widget_set_size_request (entry028, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry028), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry028), 8226);

  label62 = gtk_label_new (_("confirmer mot de passe"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed12), label62, 368, 136);
  gtk_widget_set_size_request (label62, 174, 27);

  label63 = gtk_label_new (_("cin"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed12), label63, 16, 96);
  gtk_widget_set_size_request (label63, 150, 27);

  label64 = gtk_label_new (_("GSM"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed12), label64, 16, 136);
  gtk_widget_set_size_request (label64, 150, 27);

  label65 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed12), label65, 392, 96);
  gtk_widget_set_size_request (label65, 150, 27);

  retour_modif_ag = gtk_button_new ();
  gtk_widget_show (retour_modif_ag);
  gtk_fixed_put (GTK_FIXED (fixed12), retour_modif_ag, 656, 248);
  gtk_widget_set_size_request (retour_modif_ag, 30, 30);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (retour_modif_ag), image11);

  save = gtk_button_new ();
  gtk_widget_show (save);
  gtk_fixed_put (GTK_FIXED (fixed12), save, 104, 208);
  gtk_widget_set_size_request (save, 100, 50);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (save), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image12 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox6), image12, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("save"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox6), label27, FALSE, FALSE, 0);

  label02 = gtk_label_new ("");
  gtk_widget_show (label02);
  gtk_fixed_put (GTK_FIXED (fixed12), label02, 288, 216);
  gtk_widget_set_size_request (label02, 280, 33);

  g_signal_connect ((gpointer) modif_ag, "show",
                    G_CALLBACK (on_modif_ag_show),
                    NULL);
  g_signal_connect ((gpointer) retour_modif_ag, "clicked",
                    G_CALLBACK (on_retour_modif_ag_clicked),
                    NULL);
  g_signal_connect ((gpointer) save, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_ag, modif_ag, "modif_ag");
  GLADE_HOOKUP_OBJECT (modif_ag, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (modif_ag, entry026, "entry026");
  GLADE_HOOKUP_OBJECT (modif_ag, entry024, "entry024");
  GLADE_HOOKUP_OBJECT (modif_ag, entry022, "entry022");
  GLADE_HOOKUP_OBJECT (modif_ag, entry023, "entry023");
  GLADE_HOOKUP_OBJECT (modif_ag, entry021, "entry021");
  GLADE_HOOKUP_OBJECT (modif_ag, entry025, "entry025");
  GLADE_HOOKUP_OBJECT (modif_ag, label58, "label58");
  GLADE_HOOKUP_OBJECT (modif_ag, label59, "label59");
  GLADE_HOOKUP_OBJECT (modif_ag, label60, "label60");
  GLADE_HOOKUP_OBJECT (modif_ag, label61, "label61");
  GLADE_HOOKUP_OBJECT (modif_ag, entry027, "entry027");
  GLADE_HOOKUP_OBJECT (modif_ag, entry028, "entry028");
  GLADE_HOOKUP_OBJECT (modif_ag, label62, "label62");
  GLADE_HOOKUP_OBJECT (modif_ag, label63, "label63");
  GLADE_HOOKUP_OBJECT (modif_ag, label64, "label64");
  GLADE_HOOKUP_OBJECT (modif_ag, label65, "label65");
  GLADE_HOOKUP_OBJECT (modif_ag, retour_modif_ag, "retour_modif_ag");
  GLADE_HOOKUP_OBJECT (modif_ag, image11, "image11");
  GLADE_HOOKUP_OBJECT (modif_ag, save, "save");
  GLADE_HOOKUP_OBJECT (modif_ag, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modif_ag, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modif_ag, image12, "image12");
  GLADE_HOOKUP_OBJECT (modif_ag, label27, "label27");
  GLADE_HOOKUP_OBJECT (modif_ag, label02, "label02");

  return modif_ag;
}

GtkWidget*
create_validation (void)
{
  GtkWidget *validation;
  GtkWidget *fixed14;
  GtkWidget *image18;
  GtkWidget *label72;

  validation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_position (GTK_WINDOW (validation), GTK_WIN_POS_CENTER);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (validation), fixed14);

  image18 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed14), image18, 8, 40);
  gtk_widget_set_size_request (image18, 56, 45);

  label72 = gtk_label_new (_("Op\303\251ration termin\303\251 avec succ\303\250s "));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed14), label72, 0, 32);
  gtk_widget_set_size_request (label72, 328, 65);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (validation, validation, "validation");
  GLADE_HOOKUP_OBJECT (validation, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (validation, image18, "image18");
  GLADE_HOOKUP_OBJECT (validation, label72, "label72");

  return validation;
}

GtkWidget*
create_ajout_cl (void)
{
  GtkWidget *ajout_cl;
  GtkWidget *fixed16;
  GtkWidget *entry036;
  GtkWidget *entry034;
  GtkWidget *entry032;
  GtkWidget *entry033;
  GtkWidget *entry031;
  GtkWidget *entry035;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *entry037;
  GtkWidget *entry038;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *label86;
  GtkWidget *button12;
  GtkWidget *image25;
  GtkWidget *label03;
  GtkWidget *ajouter_cl;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image26;
  GtkWidget *label87;

  ajout_cl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_cl), _("ajout"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (ajout_cl), fixed16);

  entry036 = gtk_entry_new ();
  gtk_widget_show (entry036);
  gtk_fixed_put (GTK_FIXED (fixed16), entry036, 544, 56);
  gtk_widget_set_size_request (entry036, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry036), 8226);

  entry034 = gtk_entry_new ();
  gtk_widget_show (entry034);
  gtk_fixed_put (GTK_FIXED (fixed16), entry034, 168, 136);
  gtk_widget_set_size_request (entry034, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry034), 8226);

  entry032 = gtk_entry_new ();
  gtk_widget_show (entry032);
  gtk_fixed_put (GTK_FIXED (fixed16), entry032, 168, 56);
  gtk_widget_set_size_request (entry032, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry032), 8226);

  entry033 = gtk_entry_new ();
  gtk_widget_show (entry033);
  gtk_fixed_put (GTK_FIXED (fixed16), entry033, 168, 96);
  gtk_widget_set_size_request (entry033, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry033), 8226);

  entry031 = gtk_entry_new ();
  gtk_widget_show (entry031);
  gtk_fixed_put (GTK_FIXED (fixed16), entry031, 168, 16);
  gtk_widget_set_size_request (entry031, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry031), 8226);

  entry035 = gtk_entry_new ();
  gtk_widget_show (entry035);
  gtk_fixed_put (GTK_FIXED (fixed16), entry035, 544, 16);
  gtk_widget_set_size_request (entry035, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry035), 8226);

  label79 = gtk_label_new (_("prenom"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed16), label79, 16, 56);
  gtk_widget_set_size_request (label79, 150, 27);

  label80 = gtk_label_new (_("nom"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed16), label80, 16, 16);
  gtk_widget_set_size_request (label80, 150, 27);

  label81 = gtk_label_new (_("adresse"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed16), label81, 392, 16);
  gtk_widget_set_size_request (label81, 150, 27);

  label82 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed16), label82, 392, 56);
  gtk_widget_set_size_request (label82, 150, 27);

  entry037 = gtk_entry_new ();
  gtk_widget_show (entry037);
  gtk_fixed_put (GTK_FIXED (fixed16), entry037, 544, 96);
  gtk_widget_set_size_request (entry037, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry037), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry037), 8226);

  entry038 = gtk_entry_new ();
  gtk_widget_show (entry038);
  gtk_fixed_put (GTK_FIXED (fixed16), entry038, 544, 136);
  gtk_widget_set_size_request (entry038, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry038), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry038), 8226);

  label83 = gtk_label_new (_("confirmer mot de passe"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed16), label83, 368, 136);
  gtk_widget_set_size_request (label83, 174, 27);

  label84 = gtk_label_new (_("cin"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed16), label84, 16, 96);
  gtk_widget_set_size_request (label84, 150, 27);

  label85 = gtk_label_new (_("GSM"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed16), label85, 16, 136);
  gtk_widget_set_size_request (label85, 150, 27);

  label86 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed16), label86, 392, 96);
  gtk_widget_set_size_request (label86, 150, 27);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed16), button12, 664, 264);
  gtk_widget_set_size_request (button12, 30, 30);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_container_add (GTK_CONTAINER (button12), image25);

  label03 = gtk_label_new ("");
  gtk_widget_show (label03);
  gtk_fixed_put (GTK_FIXED (fixed16), label03, 344, 240);
  gtk_widget_set_size_request (label03, 280, 33);

  ajouter_cl = gtk_button_new ();
  gtk_widget_show (ajouter_cl);
  gtk_fixed_put (GTK_FIXED (fixed16), ajouter_cl, 168, 232);
  gtk_widget_set_size_request (ajouter_cl, 150, 50);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (ajouter_cl), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox13), image26, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox13), label87, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_retour_ag_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_cl, "clicked",
                    G_CALLBACK (on_ajouter_cl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_cl, ajout_cl, "ajout_cl");
  GLADE_HOOKUP_OBJECT (ajout_cl, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry036, "entry036");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry034, "entry034");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry032, "entry032");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry033, "entry033");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry031, "entry031");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry035, "entry035");
  GLADE_HOOKUP_OBJECT (ajout_cl, label79, "label79");
  GLADE_HOOKUP_OBJECT (ajout_cl, label80, "label80");
  GLADE_HOOKUP_OBJECT (ajout_cl, label81, "label81");
  GLADE_HOOKUP_OBJECT (ajout_cl, label82, "label82");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry037, "entry037");
  GLADE_HOOKUP_OBJECT (ajout_cl, entry038, "entry038");
  GLADE_HOOKUP_OBJECT (ajout_cl, label83, "label83");
  GLADE_HOOKUP_OBJECT (ajout_cl, label84, "label84");
  GLADE_HOOKUP_OBJECT (ajout_cl, label85, "label85");
  GLADE_HOOKUP_OBJECT (ajout_cl, label86, "label86");
  GLADE_HOOKUP_OBJECT (ajout_cl, button12, "button12");
  GLADE_HOOKUP_OBJECT (ajout_cl, image25, "image25");
  GLADE_HOOKUP_OBJECT (ajout_cl, label03, "label03");
  GLADE_HOOKUP_OBJECT (ajout_cl, ajouter_cl, "ajouter_cl");
  GLADE_HOOKUP_OBJECT (ajout_cl, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ajout_cl, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajout_cl, image26, "image26");
  GLADE_HOOKUP_OBJECT (ajout_cl, label87, "label87");

  return ajout_cl;
}

